networks:
  safe-tranx:
services: 
  app: 
    build: .
    depends_on: 
      - postgres
    ports: 
      - '4001:4001'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
        - safe-tranx
    command: npm run start:dev

  postgres:
    image: postgres:15.6
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - data-db:/var/lib/postgresql/data 
    environment: 
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    networks:
        - safe-tranx

volumes:
  data-db: 
